# Generated by Django 5.2.8 on 2025-12-07 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('mode', models.CharField(default='fast', max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('total_findings', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('findings_json', models.TextField(default='[]')),
                ('full_result_json', models.TextField(default='{}')),
                ('scan_duration', models.FloatField(default=0.0)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code Scan',
                'verbose_name_plural': 'Code Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
