# Generated by Django 5.2.8 on 2026-01-19 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_scan', '0003_alter_scanproject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField(unique=True)),
                ('account_login', models.CharField(max_length=255)),
                ('account_type', models.CharField(default='User', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_installations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
