# Generated by Django 5.2.8 on 2026-01-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
