# Generated by Django 5.2.8 on 2025-11-29 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('social_handles_json', models.TextField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_results_json', models.TextField(blank=True, null=True)),
                ('intelx_results_json', models.TextField(blank=True, null=True)),
                ('breach_data_json', models.TextField(blank=True, null=True)),
                ('social_results_json', models.TextField(blank=True, null=True)),
                ('phone_results_json', models.TextField(blank=True, null=True)),
                ('ip_results_json', models.TextField(blank=True, null=True)),
                ('public_records_json', models.TextField(blank=True, null=True)),
                ('email_pattern_json', models.TextField(blank=True, null=True)),
                ('darkweb_scan_json', models.TextField(blank=True, null=True)),
                ('correlation_json', models.TextField(blank=True, null=True)),
                ('risk_breakdown_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scanner.scanhistory')),
            ],
        ),
        migrations.AddIndex(
            model_name='scanhistory',
            index=models.Index(fields=['-created_at'], name='scanner_sca_created_912ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='scanhistory',
            index=models.Index(fields=['user', '-created_at'], name='scanner_sca_user_id_8c123c_idx'),
        ),
    ]
